### ISSUE TITLE
Empty Download Folder

### ISSUE THREAD

**Issue by kieranwheatley** [im-richard/hogwartsrp#32]
Hi there,

I downloaded the folder to find there was nothing in it. I was hoping to use this to see if/how you restrict spells to levels so I couldn't implement it for my server. Is there any way I could see them?

**Comment by im-richard** [comment]
I'm writing the hogwarts RP gamemode from the ground up myself since they've all relied on DarkRP in the past.

For spells, I assume you're using the rewrite wand addon.
If you open up the spell file within `lua\hpwrewrite\spells\harrypotter` folder and look at the code, the variables at the top should start with

`local Spell = { }`

To specify a minimum required year, you'd just add

`Spell.Level = 3` somewhere under the above code and restart your server.
Then any player who obtains that particular spell, will need year 3 (level 3 within whatever XP addon you're using) in order to have it.

There's a lot of other things that need to be done to get the system to run smoothly all-around so that students are actually the proper year, setting up the F4 so the spell can be dropped, etc. But this is why I'm re-writing from the ground up so future servers have an all-in-one package vs spending weeks setting things up.

**Comment by kieranwheatley** [comment]
Hi, thanks for the quick response!

I have tried doing the Spell.Level in the spell files but it doesn't work, it still lets anyone learn it.
